# Generated by Django 4.1.3 on 2023-01-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=50)),
                ('iata_code', models.CharField(max_length=3)),
                ('nature', models.BooleanField()),
            ],
        ),
    ]
