# Generated by Django 4.1.3 on 2023-01-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='nature',
            new_name='domestico',
        ),
        migrations.AddField(
            model_name='route',
            name='internacional',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
