# Generated by Django 4.1.3 on 2023-01-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_rename_nature_route_domestico_route_internacional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AlterField(
            model_name='route',
            name='domestico',
            field=models.BooleanField(default=True, verbose_name='Domestico'),
        ),
        migrations.AlterField(
            model_name='route',
            name='iata_code',
            field=models.CharField(max_length=3, verbose_name='Codigo IATA'),
        ),
        migrations.AlterField(
            model_name='route',
            name='internacional',
            field=models.BooleanField(default=False, verbose_name='Internacional'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route',
            field=models.CharField(max_length=50, verbose_name='Ruta'),
        ),
    ]
