# Generated by Django 4.1.3 on 2023-01-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_route_options_alter_route_domestico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='internacional',
            field=models.BooleanField(verbose_name='Internacional'),
        ),
    ]
