# Generated by Django 4.1.3 on 2023-02-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_route_internacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
