# Generated by Django 4.1.3 on 2023-01-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_fleet_iata_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='iata_code',
            field=models.CharField(max_length=3, verbose_name='Codigo IATA'),
        ),
    ]
