# Generated by Django 4.1.3 on 2022-12-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fligths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aeropuerto', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=10)),
                ('cia_vuelo', models.CharField(max_length=10)),
                ('acft', models.CharField(max_length=10)),
                ('fecha_hora', models.DateTimeField()),
                ('ruta', models.CharField(max_length=3)),
                ('observacion', models.CharField(max_length=100)),
                ('clase', models.CharField(max_length=10)),
                ('cia', models.CharField(max_length=2)),
                ('pax', models.IntegerField()),
            ],
        ),
    ]
