# Generated by Django 4.1.3 on 2023-01-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fligths',
            name='fecha_hora',
            field=models.CharField(max_length=40),
        ),
    ]
