# Generated by Django 4.1.3 on 2023-01-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_fligths_fecha_hora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fligths',
            options={'verbose_name': 'Vuelo', 'verbose_name_plural': 'Vuelos'},
        ),
        migrations.AlterField(
            model_name='fligths',
            name='acft',
            field=models.CharField(max_length=10, verbose_name='ACFT'),
        ),
        migrations.AlterField(
            model_name='fligths',
            name='aeropuerto',
            field=models.CharField(max_length=50, verbose_name='APTO'),
        ),
        migrations.AlterField(
            model_name='fligths',
            name='cia',
            field=models.CharField(max_length=2, verbose_name='Cia'),
        ),
        migrations.AlterField(
            model_name='fligths',
            name='cia_vuelo',
            field=models.CharField(max_length=10, verbose_name='CIA-Nro. Vuelo'),
        ),
        migrations.AlterField(
            model_name='fligths',
            name='clase',
            field=models.CharField(max_length=10, verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='fligths',
            name='fecha_hora',
            field=models.CharField(max_length=40, verbose_name='Fecha - Hora'),
        ),
        migrations.AlterField(
            model_name='fligths',
            name='observacion',
            field=models.CharField(max_length=100, verbose_name='Obs.'),
        ),
        migrations.AlterField(
            model_name='fligths',
            name='pax',
            field=models.IntegerField(verbose_name='Cant. PAX'),
        ),
        migrations.AlterField(
            model_name='fligths',
            name='ruta',
            field=models.CharField(max_length=3, verbose_name='Ruta'),
        ),
        migrations.AlterField(
            model_name='fligths',
            name='tipo',
            field=models.CharField(max_length=10, verbose_name='Tipo'),
        ),
    ]
