# Generated by Django 4.1.3 on 2023-02-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_fligths_apto_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fligths',
            old_name='apto_image',
            new_name='flight_image',
        ),
    ]
