# Generated by Django 4.1.3 on 2023-02-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
            ],
        ),
    ]
