# Generated by Django 4.1.3 on 2023-02-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initial',
            options={'verbose_name': 'Inicio', 'verbose_name_plural': 'Inicio'},
        ),
        migrations.AddField(
            model_name='initial',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion'),
        ),
    ]
